### ISSUE TITLE
revert hlist addition to codecs

### ISSUE THREAD

**Issue by ahjohannessen** [oncue/remotely#110]
I think addition of hlists to `Codecs` has been more pain than anything else, compile times are staggering once your protocol grows. Honestly I do not see what value it brings about. This is the commit that introduced hlists on `Codecs`:

https://github.com/oncue/remotely/commit/a087b00149d63af808136c148af330d27df4dc95

@timperrett @stew @runarorama WDYT?

If reverting that change is is not desirable, could we then at least find a better way that does not make scalac crap out once the protocol starts to grow?

**Comment by timperrett** [comment]
@ahjohannessen im ok with reverting this out - i liked the way it was before too

**Comment by ahjohannessen** [comment]
@timperrett I can do the necessary work wrt reverting this out
