### ISSUE TITLE
Issue with macros

### ISSUE THREAD

**Issue by tpolecat** [oncue/remotely#13]
So, I ran into a few issues with the macro stuff. First, the doc needs to mention that projects need to add the paradise plugin, otherwise the macro will fail silently and the eventual reference to `.environment` on the server impl will cause a compilation failure.

```scala
addCompilerPlugin("org.scalamacros" % "paradise" % "2.0.1" cross CrossVersion.full)
```

Next, I was unable to get the macro working if I factored out the protocol. So the following works:

```scala
@GenServer(remotely.Protocol
    .empty
    .codec[String]
    .codec[scalaz.\/[String, Int]] // fqn red'd even though it's imported
    .specify1[String, scalaz.\/[String, Int]]("pop")) 
abstract class World2Server
```

but if I try to factor out the protocol thus:

```scala
package demo

object WorldProto {
  val definition = remotely.Protocol
    .empty
    .codec[String]
    .codec[scalaz.\/[String, Int]]
    .specify1[String, scalaz.\/[String, Int]]("pop")
}

@GenServer(demo.WorldProto.definition) 
abstract class World2Server
```

compilation fails with the following message:

```
/Users/rnorris/Scala/doobie-remotely/src/main/scala/demo/World2.scala:26: exception during macro expansion: 
scala.tools.reflect.ToolBoxError: reflective compilation has failed: 
object definition is not a member of package demo.WorldProto
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:315)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:249)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:416)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:419)
  at scala.reflect.macros.runtime.Evals$class.eval(Evals.scala:16)
  at scala.reflect.macros.runtime.Context.eval(Context.scala:6)
  at remotely.GenServer$.impl(GenServer.scala:57)
@GenServer(demo.WorldProto.definition) 
 ^
```

I tried putting the protocol in another compilation unit and even in another project, but it didn't make a difference. I avoid macros so I really don't know what I should expect here; hopefully it's something dumb.

**Comment by runarorama** [comment]
You cannot use a runtime value as an argument to a macro. When you say `@GenServer(foo)`, what the macro receives is literally the Scala AST `foo`. It will eval this tree, but the identifier `foo` doesn't refer to anything at this stage.

We should probably set up a skeleton project template for showing how to use these macros. In the simplest case, you can just put the full self-contained protocol definition in a block as an argument to the macro. But this requires all names to be fully qualified (or imported) in the block you pass to the macro.

The more common case is to put the protocol definition in a separate project. If you're getting the protocol definition from a JAR on the classpath, that should be available to the macro just like `scalaz` is in your example. Try that again and let me know if you run into trouble.

**Comment by tpolecat** [comment]
Aha, that makes perfect sense. Just a doc issue then, although it would be nice if lack of the plugin or wrong project structure resulted in a useful error message. Thanks!

**Comment by runarorama** [comment]
Well, a doc issue is still an issue. Leaving this open for that reason.

**Comment by timperrett** [comment]
Yeah, we should update the docs for this - should be a simple fix though and we can put the need to add the paradise plugin right up front. Thanks for pointing that out @tpolecat
