### ISSUE TITLE
creating a transport is side-effecty

### ISSUE THREAD

**Issue by stew** [oncue/remotely#21]
@tpolecat points out that NettyTransport.single(addr) is side-effecty and should probably return a Task. I tend to agree, but it might gross up the client code a bit. Open the issue for discussion before I go making this change.

**Comment by timperrett** [comment]
@stew can you paste a straw man of what the client code would look like that would make it gross?

**Comment by timperrett** [comment]
@stew this is resolve now isnt it?

**Comment by stew** [comment]
yes!
