### ISSUE TITLE
Signatures 'wrapResponse' returns invalid type parameter string

### ISSUE THREAD

**Issue by LGLO** [oncue/remotely#90]
`Signatures.wrapResponse` used by GenServer.scala returns invalid 'type parameter string' for list of parameters. There are missing parentheses around function parameters.
There is an error in SignaturesSpec.scala:
```scala
Signature("foo", List(Field("baz", "Baz"), Field("qux", "Qux")), "Zod").wrapResponse should be ("Baz,Qux => Response[Zod]")
```
should be:
```scala
Signature("foo", List(Field("baz", "Baz"), Field("qux", "Qux")), "Zod").wrapResponse should be ("(Baz,Qux) => Response[Zod]")
```

This causes error for protocols that use specify2.
Following protocol definition:
```scala
val definition = Protocol.empty
    .codec[Int]
    .specify2("f", Field.strict[Int]("a"), Field.strict[Int]("b"), Type[Int])
```
causes error during macro expansion:
```
[error] <toolbox>:1: wrong number of type parameters for method ref: [A](s: String)(implicit evidence$1: reflect.runtime.universe.TypeTag[A])remotely.Remote[A]
[error] val f = Remote.ref[Int,Int => Int]("f")
```

I can send two files to place in 'test' and 'test-server' modules that cause compile error seen above.

**Comment by adamw** [comment]
I get the same problem, `specify2` with `@GenServer` doesn't work

**Comment by ahjohannessen** [comment]
Closed by https://github.com/oncue/remotely/commit/21edf825880e2727ccab436b28de9441d7ff3070
