### ISSUE TITLE
@GenClient cannot expand method named in reserved word properly

### ISSUE THREAD

**Issue by ShengC** [oncue/remotely#94]
val definition = Protocol.empty.codec[String].specify1("type", Field.strict[String]("foo"), Type[String])

    @GenClient(definition)
    object FooClient

this throws compile error at
https://github.com/oncue/remotely/blob/master/core/src/main/scala/GenClient.scala#L46

since `type` is a reserved word.

easiest solution could be using backtick to surround the variable name, like this,

      val signatures : Set[Tree] = s.signatures.map { sig =>
          c.parse(s"""val `${sig.name}` = Remote.ref[${sig.typeString}]("${sig.name}")""")
      }

**Comment by ahjohannessen** [comment]
Closed by https://github.com/oncue/remotely/commit/21edf825880e2727ccab436b28de9441d7ff3070
